#!/bin/bash
echo "Ligando modulos"
modprobe mii ; modprobe usbnet
echo "Modulos ligados"
echo "Connecting"
dhcpcd usb0
ping -c4 8.8.8.8 || echo "Error 0000, cant connect!" && exit
echo "Connected"
exit
